# File này được cập nhật tự động bởi deploy.sh hoặc rollback.sh khi hoán đổi Blue/Green
upstream active_frontend {
    server frontend_blue:80;
}

upstream active_backend {
    server backend_blue:5000;
}
